package com.example.socialconnect.authentication.presentation

import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class AuthViewModel @Inject constructor() : ViewModel() {

    private val auth: FirebaseAuth = Firebase.auth
    private val db = Firebase.firestore

    // StateFlow for authentication state
    private val _authState = MutableStateFlow<AuthState>(AuthState.Idle)
    val authState = _authState.asStateFlow()


    fun createUserWithEmailAndPassword(email: String, password: String) {
        viewModelScope.launch {
            _authState.value = AuthState.Loading
            auth.createUserWithEmailAndPassword(email, password)
                .addOnCompleteListener { task ->
                    if (task.isSuccessful) {
                        _authState.value = AuthState.Success
                    } else {
                        _authState.value =
                            AuthState.Error(task.exception?.message ?: "Unknown error")
                    }
                }
        }
    }

    //    this function will create car object in db with uid auto-generated
    fun createUser(
        firstName: String,
        lastName: String,
        id: String = "",
        number: String,
        profilePictureLink: String,
    ) {
        val user = hashMapOf(
            "firstName" to firstName,
            "lastName" to lastName,
            "id" to id,
            "number" to number,
            "profilePictureLink" to profilePictureLink
        )
        viewModelScope.launch {
            _authState.value = AuthState.Loading
            db.collection("users")
                .add(user)
                .addOnSuccessListener { documentReference ->
                    val autoGeneratedId = documentReference.id
                    db.collection("users")
                        .document(autoGeneratedId)
                        .update("id", autoGeneratedId)
                        .addOnSuccessListener {
                            _authState.value = AuthState.Success
                        }
                        .addOnFailureListener { e ->
                            _authState.value = AuthState.Error(e.message ?: "Unknown error")
                        }
                }.addOnFailureListener { e ->
                    _authState.value = AuthState.Error(e.message ?: "Unknown error")
                }
        }
    }

    fun signInUserWithEmailAndPassword(email: String, password: String) {
        viewModelScope.launch {
            _authState.value = AuthState.Loading
            auth.signInWithEmailAndPassword(email, password)
                .addOnCompleteListener { task ->
                    if (task.isSuccessful) {
                        _authState.value = AuthState.Success
                    } else {
                        _authState.value =
                            AuthState.Error(task.exception?.message ?: "Login failed")
                    }
                }
        }
    }

    fun signOut() {
        viewModelScope.launch {
            _authState.value = AuthState.Loading
            auth.signOut()
            _authState.value = AuthState.Success
        }
    }

    fun resetState() {
        _authState.value = AuthState.Idle
    }


    val isPasswordVisible = mutableStateOf(false)
    fun togglePasswordVisibility() {
        isPasswordVisible.value = !isPasswordVisible.value
    }
}

sealed class AuthState {
    object Idle : AuthState()
    object Loading : AuthState()
    object Success : AuthState()
    data class Error(val message: String) : AuthState()
}